### ISSUE TITLE
NoMethodError: undefined method `Manager' for S3AssetDeploy:Module

### ISSUE THREAD

**Issue by tomharvey** [Loomly/s3_asset_deploy#28]
I'm running `bundle exec rake deploy:production --trace` where I've setup the exact rake task as described in the readme.

But get the below:

```
NoMethodError: undefined method `Manager' for S3AssetDeploy:Module
./lib/tasks/deploy.rake:17:in `block (2 levels) in <main>'
/Users/thomasharvey/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/Users/thomasharvey/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/Users/thomasharvey/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/Users/thomasharvey/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/thomasharvey/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `synchronize'
/Users/thomasharvey/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/thomasharvey/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/Users/thomasharvey/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/Users/thomasharvey/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/thomasharvey/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/Users/thomasharvey/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/Users/thomasharvey/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/Users/thomasharvey/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/Users/thomasharvey/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
/Users/thomasharvey/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/thomasharvey/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/Users/thomasharvey/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/Users/thomasharvey/.rvm/gems/ruby-2.7.4@gemset/bin/rake:23:in `load'
/Users/thomasharvey/.rvm/gems/ruby-2.7.4@gemset/bin/rake:23:in `<main>'
/Users/thomasharvey/.rvm/gems/ruby-2.7.4@gemset/bin/ruby_executable_hooks:22:in `eval'
/Users/thomasharvey/.rvm/gems/ruby-2.7.4@gemset/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => deploy:production

```

Ruby 2.7.4 (but I get the same with 2.6.3
bundler 2.1.4

And, I've definitely got the package installed:
```
gem list | grep s3
aws-sdk-s3 (1.102.0, 1.60.1, 1.33.0)
aws-sdk-s3control (1.40.0, 1.14.0, 1.3.0)
aws-sdk-s3outposts (1.6.0)
s3_asset_deploy (1.0.0)
```

I'll poke around myself, cos this seems weird to be broken in this way ... but thought I'd post this for posterity and in case I don't find an answer

**Comment by summera** [comment]
@tomharvey thanks for the details. Do you mind sharing the code for your rake task as well as what your Gemfile looks like for the inclusion of `s3_asset_deploy`?

**Comment by tomharvey** [comment]
lib/tasks/deploy.rake

```
require "s3_asset_deploy"

namespace :deploy do
  task precompile: :environment do
    puts "Precompiling assets..."
    sh("RAILS_ENV=production SECRET_KEY_BASE='secret key' bundle exec rake assets:precompile")
  end

  task clobber_assets: :environment do
    puts "Clobbering assets..."
    sh("RAILS_ENV=production SECRET_KEY_BASE='secret key' bundle exec rake assets:clobber")
  end

  task :production do
    Rake::Task["deploy:precompile"].invoke

    manager = S3AssetDeploy::Manager("my-s3-bucket")
    manager.deploy do
      # Perform deploy to web instances in this block.
      # How you do this will depend on where you are hosting your application and what tools you use to deploy.
    end

    Rake::Task["deploy:clobber_assets"].invoke # <-- If you are running on CI where the precompiled assets directory is ephemeral, this may be unnecessary
  end
end
```


Gemfile:
```
...
gem "s3_asset_deploy"
...
```

**Comment by summera** [comment]
@tomharvey perfect, thanks. I think this is a mistake in the "Practical Example of Usage" README, but can you try to update the task for `production` to load the rails environment, like so:

```ruby
namespace :deploy do
  task product: :environment do
    ...
  end
end
```

By using `:environment` you are telling your rake task to load the entire Rails environment so you have access to all those classes (like `S3AssetDeploy::Manager`). Let me know if that works for you.

Unrelated side note: you may want to use `require: false` in your `Gemfile` for `s3_asset_deploy` unless you always need it at runtime.

```ruby
gem "s3_asset_deploy", require: false
```

**Comment by tomharvey** [comment]
Almost - that would have been the first thing I check, but it seems like we've both become over-used to instantiating classes in non-Ruby languages :) 

PR in https://github.com/Loomly/s3_asset_deploy/pull/29 fixes the readme for future travellers who are too lazy to read what they're copy/pasting

**Comment by summera** [comment]
Wow, yep definitely an oversight. Good catch 👍
